### ISSUE TITLE
[BE] 마일스톤 목록 조회 API 구현

### ISSUE THREAD

**Issue by mistercle** [boostcamp-2020/IssueTracker-22#30]
# 이슈 명 (태스크)
- BE 마일스톤 목록 조회 API 구현

## 태스크 ID
- 6-13

## 태스크 상세 내용
- BE 마일스톤 목록 조회 API 구현

**Comment by caribouuuu** [comment]
[Task 18-3 BE 마일스톤 목록 조회 API 구현] 과 중복되어 Issue Close
